name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Sync with Upstream
        run: |
          git remote add upstream https://github.com/CybriaTech/Opium
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
